// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_FLATBUFFERS_H_
#define FLATBUFFERS_GENERATED_COMMON_FLATBUFFERS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace flatbuffers {

struct DateTimeFbs;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) DateTimeFbs FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t day_;
  uint8_t month_;
  uint16_t year_;
  uint8_t hour_;
  uint8_t minute_;
  uint8_t second_;
  int8_t padding0__;

 public:
  DateTimeFbs()
      : day_(0),
        month_(0),
        year_(0),
        hour_(0),
        minute_(0),
        second_(0),
        padding0__(0) {
    (void)padding0__;
  }
  DateTimeFbs(uint8_t _day, uint8_t _month, uint16_t _year, uint8_t _hour, uint8_t _minute, uint8_t _second)
      : day_(::flatbuffers::EndianScalar(_day)),
        month_(::flatbuffers::EndianScalar(_month)),
        year_(::flatbuffers::EndianScalar(_year)),
        hour_(::flatbuffers::EndianScalar(_hour)),
        minute_(::flatbuffers::EndianScalar(_minute)),
        second_(::flatbuffers::EndianScalar(_second)),
        padding0__(0) {
    (void)padding0__;
  }
  uint8_t day() const {
    return ::flatbuffers::EndianScalar(day_);
  }
  uint8_t month() const {
    return ::flatbuffers::EndianScalar(month_);
  }
  uint16_t year() const {
    return ::flatbuffers::EndianScalar(year_);
  }
  uint8_t hour() const {
    return ::flatbuffers::EndianScalar(hour_);
  }
  uint8_t minute() const {
    return ::flatbuffers::EndianScalar(minute_);
  }
  uint8_t second() const {
    return ::flatbuffers::EndianScalar(second_);
  }
};
FLATBUFFERS_STRUCT_END(DateTimeFbs, 8);

}  // namespace flatbuffers

#endif  // FLATBUFFERS_GENERATED_COMMON_FLATBUFFERS_H_
