#ifndef BANKTRANSACTIONS_VERIFIER_H
#define BANKTRANSACTIONS_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef BANKTRANSACTIONS_READER_H
#include "BankTransactions_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#ifndef COMMON_VERIFIER_H
#include "Common_verifier.h"
#endif
#include "flatcc/flatcc_prologue.h"

static int flatbuffers_BankFbs_verify_table(flatcc_table_verifier_descriptor_t *td);
static int flatbuffers_BankAccountFbs_verify_table(flatcc_table_verifier_descriptor_t *td);
static int flatbuffers_FundTransferFbs_verify_table(flatcc_table_verifier_descriptor_t *td);
static int flatbuffers_BankTransactionFbs_verify_table(flatcc_table_verifier_descriptor_t *td);

static inline int flatbuffers_AuthenticationCodeFbs_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, flatbuffers_AuthenticationCodeFbs_identifier, 16, 1);
}

static inline int flatbuffers_AuthenticationCodeFbs_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, flatbuffers_AuthenticationCodeFbs_type_hash, 16, 1);
}

static inline int flatbuffers_AuthenticationCodeFbs_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 16, 1);
}

static inline int flatbuffers_AuthenticationCodeFbs_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 16, 1);
}

static int flatbuffers_BankFbs_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* bank_code */)) return ret;
    return flatcc_verify_ok;
}

static inline int flatbuffers_BankFbs_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_BankFbs_identifier, &flatbuffers_BankFbs_verify_table);
}

static inline int flatbuffers_BankFbs_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_BankFbs_type_identifier, &flatbuffers_BankFbs_verify_table);
}

static inline int flatbuffers_BankFbs_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &flatbuffers_BankFbs_verify_table);
}

static inline int flatbuffers_BankFbs_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &flatbuffers_BankFbs_verify_table);
}

static int flatbuffers_BankAccountFbs_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* account_number */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* check_digit */)) return ret;
    return flatcc_verify_ok;
}

static inline int flatbuffers_BankAccountFbs_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_BankAccountFbs_identifier, &flatbuffers_BankAccountFbs_verify_table);
}

static inline int flatbuffers_BankAccountFbs_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_BankAccountFbs_type_identifier, &flatbuffers_BankAccountFbs_verify_table);
}

static inline int flatbuffers_BankAccountFbs_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &flatbuffers_BankAccountFbs_verify_table);
}

static inline int flatbuffers_BankAccountFbs_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &flatbuffers_BankAccountFbs_verify_table);
}

static int flatbuffers_FundTransferFbs_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 2) /* transfer_date */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 0, &flatbuffers_BankFbs_verify_table) /* source_bank */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 2, 0, &flatbuffers_BankAccountFbs_verify_table) /* source_bank_account */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 3, 0, &flatbuffers_BankFbs_verify_table) /* destination_bank */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 4, 0, &flatbuffers_BankAccountFbs_verify_table) /* destination_bank_account */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 4, 4) /* fee_amount */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 8, 8) /* amount_transfer */)) return ret;
    if ((ret = flatcc_verify_field(td, 7, 1, 1) /* status */)) return ret;
    if ((ret = flatcc_verify_field(td, 8, 16, 1) /* authentication_code */)) return ret;
    return flatcc_verify_ok;
}

static inline int flatbuffers_FundTransferFbs_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_FundTransferFbs_identifier, &flatbuffers_FundTransferFbs_verify_table);
}

static inline int flatbuffers_FundTransferFbs_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_FundTransferFbs_type_identifier, &flatbuffers_FundTransferFbs_verify_table);
}

static inline int flatbuffers_FundTransferFbs_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &flatbuffers_FundTransferFbs_verify_table);
}

static inline int flatbuffers_FundTransferFbs_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &flatbuffers_FundTransferFbs_verify_table);
}

static int flatbuffers_BankTransactionFbs_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &flatbuffers_FundTransferFbs_verify_table) /* transactions */)) return ret;
    return flatcc_verify_ok;
}

static inline int flatbuffers_BankTransactionFbs_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_BankTransactionFbs_identifier, &flatbuffers_BankTransactionFbs_verify_table);
}

static inline int flatbuffers_BankTransactionFbs_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, flatbuffers_BankTransactionFbs_type_identifier, &flatbuffers_BankTransactionFbs_verify_table);
}

static inline int flatbuffers_BankTransactionFbs_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &flatbuffers_BankTransactionFbs_verify_table);
}

static inline int flatbuffers_BankTransactionFbs_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &flatbuffers_BankTransactionFbs_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* BANKTRANSACTIONS_VERIFIER_H */
