#ifndef BANKTRANSACTIONS_BUILDER_H
#define BANKTRANSACTIONS_BUILDER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef BANKTRANSACTIONS_READER_H
#include "BankTransactions_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#ifndef COMMON_BUILDER_H
#include "Common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "BANK"
#undef flatbuffers_extension
#define flatbuffers_extension "bin"

#define __flatbuffers_Status_formal_args , flatbuffers_Status_enum_t v0
#define __flatbuffers_Status_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, flatbuffers_Status, flatbuffers_Status_enum_t)

#define __flatbuffers_AuthenticationCodeFbs_formal_args , const int8_t v0[16]
#define __flatbuffers_AuthenticationCodeFbs_call_args , v0
static inline flatbuffers_AuthenticationCodeFbs_t *flatbuffers_AuthenticationCodeFbs_assign(flatbuffers_AuthenticationCodeFbs_t *p, const int8_t v0[16])
{ flatbuffers_int8_array_copy(p->value, v0, 16);
  return p; }
static inline flatbuffers_AuthenticationCodeFbs_t *flatbuffers_AuthenticationCodeFbs_copy(flatbuffers_AuthenticationCodeFbs_t *p, const flatbuffers_AuthenticationCodeFbs_t *p2)
{ flatbuffers_int8_array_copy(p->value, p2->value, 16);
  return p; }
static inline flatbuffers_AuthenticationCodeFbs_t *flatbuffers_AuthenticationCodeFbs_assign_to_pe(flatbuffers_AuthenticationCodeFbs_t *p, const int8_t v0[16])
{ flatbuffers_int8_array_copy_to_pe(p->value, v0, 16);
  return p; }
static inline flatbuffers_AuthenticationCodeFbs_t *flatbuffers_AuthenticationCodeFbs_copy_to_pe(flatbuffers_AuthenticationCodeFbs_t *p, const flatbuffers_AuthenticationCodeFbs_t *p2)
{ flatbuffers_int8_array_copy_to_pe(p->value, p2->value, 16);
  return p; }
static inline flatbuffers_AuthenticationCodeFbs_t *flatbuffers_AuthenticationCodeFbs_assign_from_pe(flatbuffers_AuthenticationCodeFbs_t *p, const int8_t v0[16])
{ flatbuffers_int8_array_copy_from_pe(p->value, v0, 16);
  return p; }
static inline flatbuffers_AuthenticationCodeFbs_t *flatbuffers_AuthenticationCodeFbs_copy_from_pe(flatbuffers_AuthenticationCodeFbs_t *p, const flatbuffers_AuthenticationCodeFbs_t *p2)
{ flatbuffers_int8_array_copy_from_pe(p->value, p2->value, 16);
  return p; }
__flatbuffers_build_struct(flatbuffers_, flatbuffers_AuthenticationCodeFbs, 16, 1, flatbuffers_AuthenticationCodeFbs_file_identifier, flatbuffers_AuthenticationCodeFbs_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, flatbuffers_AuthenticationCodeFbs, flatbuffers_AuthenticationCodeFbs_t)

static const flatbuffers_voffset_t __flatbuffers_BankFbs_required[] = { 0 };
typedef flatbuffers_ref_t flatbuffers_BankFbs_ref_t;
static flatbuffers_BankFbs_ref_t flatbuffers_BankFbs_clone(flatbuffers_builder_t *B, flatbuffers_BankFbs_table_t t);
__flatbuffers_build_table(flatbuffers_, flatbuffers_BankFbs, 2)

static const flatbuffers_voffset_t __flatbuffers_BankAccountFbs_required[] = { 0 };
typedef flatbuffers_ref_t flatbuffers_BankAccountFbs_ref_t;
static flatbuffers_BankAccountFbs_ref_t flatbuffers_BankAccountFbs_clone(flatbuffers_builder_t *B, flatbuffers_BankAccountFbs_table_t t);
__flatbuffers_build_table(flatbuffers_, flatbuffers_BankAccountFbs, 2)

static const flatbuffers_voffset_t __flatbuffers_FundTransferFbs_required[] = { 0 };
typedef flatbuffers_ref_t flatbuffers_FundTransferFbs_ref_t;
static flatbuffers_FundTransferFbs_ref_t flatbuffers_FundTransferFbs_clone(flatbuffers_builder_t *B, flatbuffers_FundTransferFbs_table_t t);
__flatbuffers_build_table(flatbuffers_, flatbuffers_FundTransferFbs, 9)

static const flatbuffers_voffset_t __flatbuffers_BankTransactionFbs_required[] = { 0 };
typedef flatbuffers_ref_t flatbuffers_BankTransactionFbs_ref_t;
static flatbuffers_BankTransactionFbs_ref_t flatbuffers_BankTransactionFbs_clone(flatbuffers_builder_t *B, flatbuffers_BankTransactionFbs_table_t t);
__flatbuffers_build_table(flatbuffers_, flatbuffers_BankTransactionFbs, 1)

#define __flatbuffers_BankFbs_formal_args , flatbuffers_string_ref_t v0, int32_t v1
#define __flatbuffers_BankFbs_call_args , v0, v1
static inline flatbuffers_BankFbs_ref_t flatbuffers_BankFbs_create(flatbuffers_builder_t *B __flatbuffers_BankFbs_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, flatbuffers_BankFbs, flatbuffers_BankFbs_file_identifier, flatbuffers_BankFbs_type_identifier)

#define __flatbuffers_BankAccountFbs_formal_args , int32_t v0, uint8_t v1
#define __flatbuffers_BankAccountFbs_call_args , v0, v1
static inline flatbuffers_BankAccountFbs_ref_t flatbuffers_BankAccountFbs_create(flatbuffers_builder_t *B __flatbuffers_BankAccountFbs_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, flatbuffers_BankAccountFbs, flatbuffers_BankAccountFbs_file_identifier, flatbuffers_BankAccountFbs_type_identifier)

#define __flatbuffers_FundTransferFbs_formal_args ,\
  flatbuffers_DateTimeFbs_t *v0, flatbuffers_BankFbs_ref_t v1, flatbuffers_BankAccountFbs_ref_t v2, flatbuffers_BankFbs_ref_t v3,\
  flatbuffers_BankAccountFbs_ref_t v4, float v5, double v6, flatbuffers_Status_enum_t v7, flatbuffers_AuthenticationCodeFbs_t *v8
#define __flatbuffers_FundTransferFbs_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7, v8
static inline flatbuffers_FundTransferFbs_ref_t flatbuffers_FundTransferFbs_create(flatbuffers_builder_t *B __flatbuffers_FundTransferFbs_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, flatbuffers_FundTransferFbs, flatbuffers_FundTransferFbs_file_identifier, flatbuffers_FundTransferFbs_type_identifier)

#define __flatbuffers_BankTransactionFbs_formal_args , flatbuffers_FundTransferFbs_vec_ref_t v0
#define __flatbuffers_BankTransactionFbs_call_args , v0
static inline flatbuffers_BankTransactionFbs_ref_t flatbuffers_BankTransactionFbs_create(flatbuffers_builder_t *B __flatbuffers_BankTransactionFbs_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, flatbuffers_BankTransactionFbs, flatbuffers_BankTransactionFbs_file_identifier, flatbuffers_BankTransactionFbs_type_identifier)

__flatbuffers_build_string_field(0, flatbuffers_, flatbuffers_BankFbs_name, flatbuffers_BankFbs)
__flatbuffers_build_scalar_field(1, flatbuffers_, flatbuffers_BankFbs_bank_code, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), flatbuffers_BankFbs)

static inline flatbuffers_BankFbs_ref_t flatbuffers_BankFbs_create(flatbuffers_builder_t *B __flatbuffers_BankFbs_formal_args)
{
    if (flatbuffers_BankFbs_start(B)
        || flatbuffers_BankFbs_name_add(B, v0)
        || flatbuffers_BankFbs_bank_code_add(B, v1)) {
        return 0;
    }
    return flatbuffers_BankFbs_end(B);
}

static flatbuffers_BankFbs_ref_t flatbuffers_BankFbs_clone(flatbuffers_builder_t *B, flatbuffers_BankFbs_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (flatbuffers_BankFbs_start(B)
        || flatbuffers_BankFbs_name_pick(B, t)
        || flatbuffers_BankFbs_bank_code_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, flatbuffers_BankFbs_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, flatbuffers_BankAccountFbs_account_number, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), flatbuffers_BankAccountFbs)
__flatbuffers_build_scalar_field(1, flatbuffers_, flatbuffers_BankAccountFbs_check_digit, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), flatbuffers_BankAccountFbs)

static inline flatbuffers_BankAccountFbs_ref_t flatbuffers_BankAccountFbs_create(flatbuffers_builder_t *B __flatbuffers_BankAccountFbs_formal_args)
{
    if (flatbuffers_BankAccountFbs_start(B)
        || flatbuffers_BankAccountFbs_account_number_add(B, v0)
        || flatbuffers_BankAccountFbs_check_digit_add(B, v1)) {
        return 0;
    }
    return flatbuffers_BankAccountFbs_end(B);
}

static flatbuffers_BankAccountFbs_ref_t flatbuffers_BankAccountFbs_clone(flatbuffers_builder_t *B, flatbuffers_BankAccountFbs_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (flatbuffers_BankAccountFbs_start(B)
        || flatbuffers_BankAccountFbs_account_number_pick(B, t)
        || flatbuffers_BankAccountFbs_check_digit_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, flatbuffers_BankAccountFbs_end(B));
}

__flatbuffers_build_struct_field(0, flatbuffers_, flatbuffers_FundTransferFbs_transfer_date, flatbuffers_DateTimeFbs, 8, 2, flatbuffers_FundTransferFbs)
__flatbuffers_build_table_field(1, flatbuffers_, flatbuffers_FundTransferFbs_source_bank, flatbuffers_BankFbs, flatbuffers_FundTransferFbs)
__flatbuffers_build_table_field(2, flatbuffers_, flatbuffers_FundTransferFbs_source_bank_account, flatbuffers_BankAccountFbs, flatbuffers_FundTransferFbs)
__flatbuffers_build_table_field(3, flatbuffers_, flatbuffers_FundTransferFbs_destination_bank, flatbuffers_BankFbs, flatbuffers_FundTransferFbs)
__flatbuffers_build_table_field(4, flatbuffers_, flatbuffers_FundTransferFbs_destination_bank_account, flatbuffers_BankAccountFbs, flatbuffers_FundTransferFbs)
__flatbuffers_build_scalar_field(5, flatbuffers_, flatbuffers_FundTransferFbs_fee_amount, flatbuffers_float, float, 4, 4, 0.00000000f, flatbuffers_FundTransferFbs)
__flatbuffers_build_scalar_field(6, flatbuffers_, flatbuffers_FundTransferFbs_amount_transfer, flatbuffers_double, double, 8, 8, 0.0000000000000000, flatbuffers_FundTransferFbs)
__flatbuffers_build_scalar_field(7, flatbuffers_, flatbuffers_FundTransferFbs_status, flatbuffers_Status, flatbuffers_Status_enum_t, 1, 1, INT8_C(0), flatbuffers_FundTransferFbs)
__flatbuffers_build_struct_field(8, flatbuffers_, flatbuffers_FundTransferFbs_authentication_code, flatbuffers_AuthenticationCodeFbs, 16, 1, flatbuffers_FundTransferFbs)

static inline flatbuffers_FundTransferFbs_ref_t flatbuffers_FundTransferFbs_create(flatbuffers_builder_t *B __flatbuffers_FundTransferFbs_formal_args)
{
    if (flatbuffers_FundTransferFbs_start(B)
        || flatbuffers_FundTransferFbs_amount_transfer_add(B, v6)
        || flatbuffers_FundTransferFbs_source_bank_add(B, v1)
        || flatbuffers_FundTransferFbs_source_bank_account_add(B, v2)
        || flatbuffers_FundTransferFbs_destination_bank_add(B, v3)
        || flatbuffers_FundTransferFbs_destination_bank_account_add(B, v4)
        || flatbuffers_FundTransferFbs_fee_amount_add(B, v5)
        || flatbuffers_FundTransferFbs_transfer_date_add(B, v0)
        || flatbuffers_FundTransferFbs_status_add(B, v7)
        || flatbuffers_FundTransferFbs_authentication_code_add(B, v8)) {
        return 0;
    }
    return flatbuffers_FundTransferFbs_end(B);
}

static flatbuffers_FundTransferFbs_ref_t flatbuffers_FundTransferFbs_clone(flatbuffers_builder_t *B, flatbuffers_FundTransferFbs_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (flatbuffers_FundTransferFbs_start(B)
        || flatbuffers_FundTransferFbs_amount_transfer_pick(B, t)
        || flatbuffers_FundTransferFbs_source_bank_pick(B, t)
        || flatbuffers_FundTransferFbs_source_bank_account_pick(B, t)
        || flatbuffers_FundTransferFbs_destination_bank_pick(B, t)
        || flatbuffers_FundTransferFbs_destination_bank_account_pick(B, t)
        || flatbuffers_FundTransferFbs_fee_amount_pick(B, t)
        || flatbuffers_FundTransferFbs_transfer_date_pick(B, t)
        || flatbuffers_FundTransferFbs_status_pick(B, t)
        || flatbuffers_FundTransferFbs_authentication_code_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, flatbuffers_FundTransferFbs_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, flatbuffers_BankTransactionFbs_transactions, flatbuffers_FundTransferFbs, flatbuffers_BankTransactionFbs)

static inline flatbuffers_BankTransactionFbs_ref_t flatbuffers_BankTransactionFbs_create(flatbuffers_builder_t *B __flatbuffers_BankTransactionFbs_formal_args)
{
    if (flatbuffers_BankTransactionFbs_start(B)
        || flatbuffers_BankTransactionFbs_transactions_add(B, v0)) {
        return 0;
    }
    return flatbuffers_BankTransactionFbs_end(B);
}

static flatbuffers_BankTransactionFbs_ref_t flatbuffers_BankTransactionFbs_clone(flatbuffers_builder_t *B, flatbuffers_BankTransactionFbs_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (flatbuffers_BankTransactionFbs_start(B)
        || flatbuffers_BankTransactionFbs_transactions_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, flatbuffers_BankTransactionFbs_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* BANKTRANSACTIONS_BUILDER_H */
