#ifndef COMMON_VERIFIER_H
#define COMMON_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef COMMON_READER_H
#include "Common_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"


static inline int flatbuffers_DateTimeFbs_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, flatbuffers_DateTimeFbs_identifier, 8, 2);
}

static inline int flatbuffers_DateTimeFbs_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, flatbuffers_DateTimeFbs_type_hash, 8, 2);
}

static inline int flatbuffers_DateTimeFbs_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int flatbuffers_DateTimeFbs_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* COMMON_VERIFIER_H */
