// automatically generated by the FlatBuffers compiler, do not modify

package br.com.rbcti.flatbuffers.tb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BankAccountFbs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BankAccountFbs getRootAsBankAccountFbs(ByteBuffer _bb) { return getRootAsBankAccountFbs(_bb, new BankAccountFbs()); }
  public static BankAccountFbs getRootAsBankAccountFbs(ByteBuffer _bb, BankAccountFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BankAccountFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int accountNumber() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int checkDigit() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createBankAccountFbs(FlatBufferBuilder builder,
      int accountNumber,
      int checkDigit) {
    builder.startTable(2);
    BankAccountFbs.addAccountNumber(builder, accountNumber);
    BankAccountFbs.addCheckDigit(builder, checkDigit);
    return BankAccountFbs.endBankAccountFbs(builder);
  }

  public static void startBankAccountFbs(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addAccountNumber(FlatBufferBuilder builder, int accountNumber) { builder.addInt(0, accountNumber, 0); }
  public static void addCheckDigit(FlatBufferBuilder builder, int checkDigit) { builder.addByte(1, (byte) checkDigit, (byte) 0); }
  public static int endBankAccountFbs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BankAccountFbs get(int j) { return get(new BankAccountFbs(), j); }
    public BankAccountFbs get(BankAccountFbs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

