// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class AuthenticationCodeFbs extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AuthenticationCodeFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte value(int j) { return bb.get(bb_pos + 0 + j * 1); }

  public static int createAuthenticationCodeFbs(FlatBufferBuilder builder, byte[] value) {
    builder.prep(1, 16);
    for (int _idx0 = 16; _idx0 > 0; _idx0--) {
      builder.putByte(value[_idx0-1]);
    }
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AuthenticationCodeFbs get(int j) { return get(new AuthenticationCodeFbs(), j); }
    public AuthenticationCodeFbs get(AuthenticationCodeFbs obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

