// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BankTransactionFbs extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BankTransactionFbs getRootAsBankTransactionFbs(ByteBuffer _bb) { return getRootAsBankTransactionFbs(_bb, new BankTransactionFbs()); }
  public static BankTransactionFbs getRootAsBankTransactionFbs(ByteBuffer _bb, BankTransactionFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean BankTransactionFbsBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "BANK"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BankTransactionFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flatbuffers.FundTransferFbs transactions(int j) { return transactions(new flatbuffers.FundTransferFbs(), j); }
  public flatbuffers.FundTransferFbs transactions(flatbuffers.FundTransferFbs obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int transactionsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public flatbuffers.FundTransferFbs.Vector transactionsVector() { return transactionsVector(new flatbuffers.FundTransferFbs.Vector()); }
  public flatbuffers.FundTransferFbs.Vector transactionsVector(flatbuffers.FundTransferFbs.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createBankTransactionFbs(FlatBufferBuilder builder,
      int transactionsOffset) {
    builder.startTable(1);
    BankTransactionFbs.addTransactions(builder, transactionsOffset);
    return BankTransactionFbs.endBankTransactionFbs(builder);
  }

  public static void startBankTransactionFbs(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTransactions(FlatBufferBuilder builder, int transactionsOffset) { builder.addOffset(0, transactionsOffset, 0); }
  public static int createTransactionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTransactionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBankTransactionFbs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBankTransactionFbsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "BANK"); }
  public static void finishSizePrefixedBankTransactionFbsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "BANK"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BankTransactionFbs get(int j) { return get(new BankTransactionFbs(), j); }
    public BankTransactionFbs get(BankTransactionFbs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

