// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers;

@SuppressWarnings("unused")
public final class Status {
  private Status() { }
  public static final byte PENDING = 0;
  public static final byte CONFIRMED = 1;
  public static final byte CANCELED = 2;

  public static final String[] names = { "PENDING", "CONFIRMED", "CANCELED", };

  public static String name(int e) { return names[e]; }
}

